In [1]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import r2_score
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import random as r

In [2]:
data=pd.read_csv("train.csv", na_values=' ')
data
data.Dependents.unique()
data
# y
# data.isnull().sum().sort_values(ascending=False)
data = data.fillna(1)

In [4]:
def enc(df):
    df.replace(to_replace="Male",value=1,inplace=True)
    df.replace(to_replace="Female",value=0,inplace=True)
    df.replace(to_replace="Yes",value=1,inplace=True)
    df.replace(to_replace="No",value=0,inplace=True)
    df.replace(to_replace="Urban",value=1,inplace=True)
    df.replace(to_replace="Rural",value=0,inplace=True)
    df.replace(to_replace="Semiurban",value=2,inplace=True)
    df.replace(to_replace="Graduate",value=1,inplace=True)
    df.replace(to_replace="Not Graduate",value=0,inplace=True)
    df.replace(to_replace="Y",value=1,inplace=True)
    df.replace(to_replace="N",value=0,inplace=True)
    df.replace(to_replace="3+",value=4,inplace=True)
#     df.replace(to_replace=" ",value=0,inplace=True)
    
enc(data)
# enc(y)
data
y=data["Loan_Status"]
# data.dropna()
data.drop("Loan_Status",axis=1,inplace=True)
data

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,1,0,0,1,0,5849,0.0,1.0,360.0,1.0,1
1,1,1,1,1,0,4583,1508.0,128.0,360.0,1.0,0
2,1,1,0,1,1,3000,0.0,66.0,360.0,1.0,1
3,1,1,0,0,0,2583,2358.0,120.0,360.0,1.0,1
4,1,0,0,1,0,6000,0.0,141.0,360.0,1.0,1
...,...,...,...,...,...,...,...,...,...,...,...
609,0,0,0,1,0,2900,0.0,71.0,360.0,1.0,0
610,1,1,4,1,0,4106,0.0,40.0,180.0,1.0,0
611,1,1,1,1,0,8072,240.0,253.0,360.0,1.0,1
612,1,1,2,1,0,7583,0.0,187.0,360.0,1.0,1
613,0,0,0,1,1,4583,0.0,133.0,360.0,0.0,2

In [15]:
aad=[]
for i in range(data.shape[0]):
    ran=r.randint(1,999999999999)
    print(ran)
    aad.append(ran)

287010457289
118986289645
662583544596
646243595636
583486395258
677651788571
924841518028
888516874558
862990831237
281910066147
293862760132
125171800574
620146937538
965623888551
893625489967
571914679897
722036987089
83416618592
383821422640
396608730318
402178339659
586030822231
315943725763
653233378082
320663988789
267655135969
99047086904
830533625339
657260522848
856862352101
267675948622
529502084007
697482871308
542037585064
110699510709
387340811674
625814539152
632946065751
382117257670
447624720264
417423390843
151983514063
52581558912
809262984961
668486432239
589805530344
259737605039
312405595135
951772505613
420767017637
133686736284
170690711519
896632789690
889898211587
31066256982
739700207703
487402654743
958331918936
485471060256
581802868420
866489249554
943499052541
551515219634
88539152770
584775179798
823400988563
261040634147
936501685054
558173535068
857833287074
251428481448
876250677977
527878769186
347187534508
148933214368
671697198619
679008605808
602190949152
677876339145
525832133022
538692423177
725247607741
305172268131
497601718146
964012680421
95548443060
393830401053
983841473018
995712582717
793139795988
925733038934
311829000628
956192231490
992784820791
511476727262
655941237281
652087579398
268180899941
926787112253
989772383673
975138267152
447603157436
43120440101
594959215976
775923795393
104708052408
448016019977
153606910230
418785688498
704281403388
457951255039
139517060957
778226107137
765987405704
92849794625
376352576399
154581039198
864124236653
408955521995
669299310959
348053878337
397138897266
647587976217
873713787132
559093157930
287519177469
561915449161
905859906756
729769056597
941928233116
224411678034
146058508443
523367894310
222877364660
98684756280
700287968848
754742609227
548256993403
126974242417
881169552405
569824806365
694259558894
249157128736
658444968794
947095922408
980714489987
242671441916
683563062501
776192251981
75028977170
767913330057
340555081530
488043778981
434938215731
34958708445
264041717603
424267208298
84603779462
7003087062
539758110438
670070162448
377771182435
854517781770
761247153992
660300363155
697352206526
803780997058
696792052285
737560734399
47732512772
434003878541
436744570138
754564240354
617671828599
788912685306
84249302509
824497782131
690549329532
381487239358
308178738773
749215056719
98210393708
241379108256
584323674322
142039538644
657476963732
6319835474
471371054840
702843565205
690222473995
325494648982
240195664705
907928538146
698818277606
17801995340
188096927312
207766588507
760603616943
903165205237
125739542979
518727145274
732722437401
386747294382
419106964460
966455792058
272999264958
280451725210
660791177245
598856967916
474113739042
183613826195
817984353085
129470103077
64601427624
692152680926
908602515287
663144561282
446018601731
902282077407
264891444755
514867279688
325436460482
584898196620
463250181134
306508782912
191133345351
492048724807
132068920892
501412872988
272916179429
97673316470
532212018476
241826962581
826139151176
738308778389
309058254988
618560691251
565601120573
591292594763
681624378769
848651314856
327140056017
534236480459
459968720116
200450560818
554545550770
973184566699
938780627458
468497902372
605459195845
69277418824
279468292109
671123457689
868304582832
789972650239
908975821214
989236317505
973554749234
137013728935
605183426673
891075716930
335141440898
140090535016
686831780404
969543205692
429941748268
820133355620
920073285878
661489449190
543844711232
730160375823
249602270846
484367376015
457771535136
975471581090
6518724493
330958475778
216216897156
283046628008
737425829271
978342374962
426415024454
479617874421
487367893838
491233626635
259346261304
113676567328
101755236484
86101815730
476488048256
120119487158
23334964060
156811934778
171053562215
558470071608
925588828167
274382942929
79623842419
818772012502
515667601184
692619872338
758760335338
385749441863
710386184956
470821308790
495189640949
835774466872
277466006367
505399814806
573545106733
258133511987
462244120596
378710952364
51333615902
637959402090
54094425039
451406108246
58981767594
947985970410
52204662822
996312231641
483862071495
528629970625
211701836106
886271732446
887587568593
922522403082
106156125716
292238474335
736663485959
919412906489
693449336433
356599353315
787044544329
673564870043
258666293270
179050451182
581703555857
474443225391
722609994281
766818996798
548854503942
499695777673
711889038036
324038052346
937326731896
689379626349
259736987919
786265935829
556653003144
654365115194
534755078625
777970104736
833658307978
15269106773
475595451832
615696442121
956914776272
109459301813
747306327302
2563547595
600909912842
56189122135
686841576731
155197973926
622827898881
357666660005
136303202129
560434595663
291210275676
551509632375
290754965137
214545582851
46508879563
882962505034
701045189352
235456147486
784849719265
482503365993
514147643104
678765686114
517801578979
84619612493
427619134198
696531799753
936993833798
157482040467
651955295688
990265997401
271411440333
398202179889
50454031486
959784141572
610665643160
80947022358
231671981673
975756464386
674975420935
360735926036
510470931137
505910894756
935255242913
153030540951
687604010761
452063638990
43821773481
432901670409
615651450743
690192557241
734967941724
654410228031
747843701344
556174583757
320593039499
451191486128
977385993180
500495492990
201223995682
601872546224
360447630717
939254528498
447590385980
61414278454
393533183415
836637849256
433137240592
800520988910
684077533187
728456124938
202332712386
840236743231
350945939315
713722563148
716293285637
609294724966
449276141378
538733184192
942668206907
288994702858
648779367529
186645713547
696448285451
120591215483
898135269438
813778023780
759870586849
514372625379
101001935510
614873439040
562956836763
162466740477
281453153891
153819282271
669694203750
424570389331
247538793612
392912128852
471654549691
615752905848
802655660629
382417133353
803266891111
458868375414
907143316348
656067595409
686871731532
39400174555
959696468098
169875318890
714441297870
282589687650
969394208280
338320904287
454235538291
650667443648
774616933807
1008892298
298236434697
644134822358
46416883407
519473793720
17973183504
53437999278
484855577741
938533607052
778260348837
143209413920
328720548447
82399464950
195233785479
658158087975
757545060262
306057073971
819028668810
422406817342
488247025390
744123088362
259560825084
962002662249
44214661452
414620979084
127380600525
344612951381
513821752765
893325228750
387042118255
977776422863
737961735553
264149788241
572059316974
549848489142
354006553126
953851450164
523409626008
667209811848
842235925107
469977127860
578389039525
460500827354
874168652788
990962842248
802464877583
84662576081
308583060723
89106645425
86456241094
478147498230
107145943235
319999603785
425694246925
150205993991
690883039638
256201885740
10861157134
110946056946
989658030545
45056982791
858330673156
955461978688
235405771051
752163172631
629868513941
449007023236
650771736549
156497751725
612044067945
447944633013
854254010552
1951671084
281915532573
837537960058
597052944222
866355492428
582181079707
473785856582
63040845270
106071404056
143371065251
161474867942
449275798726
900840212287
618243074343
219184859595
211974101886
147670034360
704271751779
766416711713
861785538050
720459559047
655451117939
124254279095
399663817653
207918253314
347971392862
894741196397
6117120531
120933776008
486769847831
175101016803
747347974365
382757607023
181190901480
980598977111
481430485145
979605874008
922155168144
695872078112
747860960204
291368508149
323325576257
278386846857
512496756050
157326067149
946807002937
839708820773
386511082559
114445639586
904420908284
301018876373
548091090729
629547524043
874944116050
799198953007
252379967169
153635681270
856607270720
14136965130
745984006546
226712751053
644302151252
169261862427
246738847348
99948957326
771837973487

In [13]:
aad

[851396917631,
 365286832894,
 723757880988,
 178962543314,
 973748718793,
 531668685511,
 87597805908,
 294957673941,
 621180824433,
 630241357301,
 273748441523,
 816571777814,
 25427050046,
 300519746857,
 956945774880,
 44525159744,
 386538406043,
 574037470115,
 825655937900,
 641009812966,
 405009481186,
 263107444573,
 660262218484,
 259603786185,
 98593609592,
 123952524899,
 298248386524,
 589714992197,
 874647865671,
 160080354567,
 628645751746,
 104994499219,
 356590906122,
 326991482036,
 488656248420,
 135537620693,
 690428150413,
 685899962381,
 315840211582,
 292940336452,
 723599467778,
 571820534913,
 756358155963,
 130746667774,
 425287884789,
 230990754072,
 758835219530,
 49402610348,
 123576950672,
 876421287695,
 656642955655,
 672310483484,
 350079901122,
 525937314382,
 628397847795,
 444338672634,
 973544105341,
 306094268308,
 549456313597,
 671898652468,
 995329894247,
 230490328346,
 610622447838,
 150943946505,
 325399482635,
 432081353347,
 371654215334,
 293964193,
 616052270584,
 20083767445,
 898238092696,
 158328809122,
 991678832153,
 88095186265,
 860195893858,
 104450190598,
 287641584756,
 974510928074,
 865393485180,
 797914982172,
 263723356331,
 572679403322,
 782149530157,
 846393390470,
 241154789042,
 390688774160,
 231607247035,
 841232061164,
 616753756213,
 623988891603,
 173095313630,
 532462237345,
 962264584331,
 892074469200,
 730333014770,
 548174045678,
 272754060005,
 669816712617,
 364348368370,
 851712504505,
 843116011663,
 191069548115,
 662117047181,
 624608994876,
 30082039064,
 562857920949,
 730921670597,
 405753983449,
 170432794350,
 26063366199,
 348110486212,
 846342762105,
 866233571694,
 958947039817,
 639029706901,
 751044030844,
 440038700819,
 980809994816,
 942067799112,
 31136305946,
 444545977481,
 800718783694,
 122479207679,
 134868360481,
 546048818661,
 364067426241,
 584594764874,
 983840389535,
 446915064549,
 135754502901,
 878957023106,
 425482129857,
 325654872701,
 281085832846,
 340628075246,
 589955347576,
 229055374209,
 172196961550,
 237987365661,
 901035586057,
 712124681590,
 807302900859,
 158982802836,
 964692303398,
 706164228163,
 743847978402,
 976691044528,
 424998169241,
 428993434848,
 693631061740,
 208030678944,
 17640817389,
 330354301089,
 815859028936,
 260190513303,
 981690144020,
 713679609593,
 422125214392,
 300800189905,
 3947825703,
 531297892424,
 533417576177,
 406289966190,
 645758307987,
 413492225016,
 735383630863,
 453151575480,
 144147437384,
 735114405868,
 565763043417,
 247074187165,
 286778944369,
 141826333438,
 25712417965,
 540106416612,
 968832960734,
 562453131958,
 743632525029,
 303640459887,
 948018090624,
 222617949171,
 796341813886,
 57341841373,
 638452844596,
 808839429686,
 852965456628,
 719045735334,
 376201462157,
 520585320139,
 663778839767,
 376302754830,
 484229414735,
 892178563495,
 601818752317,
 50996042286,
 607167099589,
 731749835544,
 642112545746,
 896686992251,
 67055597002,
 683026601272,
 820832602899,
 220799577407,
 733593741552,
 933031050484,
 872245867395,
 201018735633,
 70925127,
 268306649606,
 545658265566,
 320795381812,
 981116615589,
 940007419102,
 137222848154,
 461928802036,
 428434248640,
 550623203249,
 644326196052,
 888545621427,
 550497441301,
 841689913208,
 619637295363,
 194727981363,
 875679505576,
 520953458727,
 417102400501,
 312482750962,
 133454836700,
 168638706369,
 742312970145,
 783779622917,
 775063319348,
 25854875144,
 445128484235,
 610012243533,
 442333271817,
 452365322273,
 111002880508,
 269340743959,
 937254029697,
 16786908395,
 808586566109,
 591427171806,
 481510847114,
 665217450389,
 54692330903,
 313641551689,
 190019809855,
 432318942177,
 425437499495,
 19383794687,
 179793074601,
 511920135918,
 496017375650,
 212812793362,
 841384937771,
 746473893887,
 591987975133,
 824397735673,
 240975210008,
 638162251223,
 256941341710,
 667551589164,
 130987089517,
 941141949606,
 197994639498,
 664237489379,
 713163702569,
 205039950407,
 644183232090,
 69214592526,
 150786278466,
 547244744349,
 244417002290,
 182348003118,
 95568587854,
 812995404784,
 127142126948,
 92077809511,
 69454306141,
 744311864733,
 571068312686,
 929762463159,
 490182499562,
 174376735534,
 790013899353,
 359936366279,
 109899007181,
 536460464864,
 876239058581,
 863058752994,
 224284225148,
 709333002997,
 657962535573,
 633400855417,
 434644584526,
 425744388040,
 887086734319,
 873120999973,
 982982595462,
 499544013965,
 616131609728,
 501442452460,
 221872958754,
 463123249611,
 660948545271,
 318744518878,
 469515735432,
 111520742744,
 518267308528,
 480294270922,
 454922801260,
 491226212713,
 268005960403,
 663477684579,
 626283020604,
 906556379890,
 916690493595,
 984426707659,
 252557749704,
 143201349989,
 812523032072,
 163739240715,
 898086611411,
 332003510412,
 792369095256,
 281067949037,
 923564637127,
 152812874914,
 883011934160,
 662521769809,
 514938485368,
 420778725061,
 925701094082,
 791724452345,
 537285045076,
 384854967204,
 459542993191,
 494990344050,
 635144597338,
 469893161060,
 52304302680,
 890083953548,
 427864070134,
 100379594136,
 249416777935,
 718235748250,
 328625064404,
 246406080467,
 600997991010,
 105561175001,
 971605950425,
 774514324776,
 890271950231,
 534500041820,
 961654324343,
 174945058973,
 765365016945,
 621708421593,
 831485696665,
 222262735416,
 842885782561,
 105651223623,
 221166131966,
 800579615275,
 869287138937,
 431119407832,
 144563600936,
 35756195241,
 520531324511,
 274425413433,
 260013219486,
 76532406885,
 36847705392,
 752310642008,
 674786312968,
 635537689426,
 620767883625,
 675549490223,
 489130404578,
 96074921242,
 91292034497,
 100999508968,
 7003504356,
 391118404189,
 541313843571,
 460971816372,
 527059283319,
 101778128585,
 269456738745,
 143074324669,
 207585047397,
 583677493971,
 189347648757,
 580715506376,
 742499345275,
 586449132064,
 673575445334,
 25884436863,
 72782461152,
 481624836047,
 612174382699,
 49609362040,
 882970991536,
 200007321856,
 86709931480,
 633156910714,
 379423898043,
 586517655401,
 693670312102,
 459266922169,
 808832202463,
 172833482758,
 411082104924,
 745664998199,
 697931193023,
 131254741700,
 105562813679,
 663443469652,
 234169997501,
 447798172444,
 158624389205,
 299560683700,
 794688996145,
 171191859112,
 483065572816,
 821258466645,
 617970828541,
 908352595052,
 755900907133,
 404125932990,
 214814931468,
 579751263794,
 248580637781,
 222998071561,
 818455715748,
 814379446921,
 188721967102,
 22542865327,
 486898839682,
 894709388463,
 680442680949,
 349746661073,
 819897408774,
 516052905227,
 979314507115,
 991503125925,
 136274871892,
 654357541249,
 58503981862,
 185269534996,
 758476200610,
 29853865444,
 448226725741,
 576102156919,
 240980083500,
 459326657922,
 979910088406,
 392162396724,
 21448395549,
 931513976816,
 785579518442,
 848383963816,
 733477390338,
 57027704673,
 106336756334,
 454404152881,
 626149233629,
 127974122838,
 945495586702,
 796914987434,
 788449043323,
 597405882101,
 215930430560,
 148491934237,
 641181739035,
 283443626553,
 556136948612,
 57206221159,
 785522885927,
 72157314175,
 814969247303,
 547607806730,
 744280915920,
 207485546801,
 987874286341,
 82387881198,
 172963757179,
 903071089033,
 101310541918,
 256521975833,
 467913007253,
 801031919748,
 275616818102,
 710418883672,
 264521305035,
 287072152625,
 739244733036,
 774813425308,
 692528342540,
 242363364469,
 585297241810,
 835793794215,
 411728087904,
 808850698427,
 765273756184,
 583486162976,
 984617001531,
 552720515704,
 923220204313,
 408573576052,
 697081958023,
 205346541298,
 258055437850,
 941826335761,
 272741274870,
 500903485806,
 426058220621,
 26803242300,
 388571743837,
 764897590641,
 89872921236,
 399343906979,
 514451996872,
 555233937547,
 300557866471,
 662017344527,
 51919293387,
 565761258847,
 652885869760,
 359783040203,
 793696928364,
 935778800569,
 917458764535,
 59474161783,
 725119765850,
 522218076548,
 60016747476,
 308119391045,
 193986563693,
 495462570941,
 753008574568,
 783328820504,
 614175629540,
 593913493904,
 715169454821,
 714723652764,
 632117449193,
 346901824920,
 177725114227,
 496406259118,
 467138647776,
 853294605062,
 265452767332,
 49287160823,
 753976959953,
 796997146132,
 750564920911,
 963742115956,
 247384633780,
 866238560107,
 563181475667,
 103820765157,
 964254565327,
 174139723949,
 292786919772,
 339984231480,
 943203572805,
 581729194138,
 446154916893,
 920220458682,
 943945937844,
 674049031348,
 657444682622,
 702799176962,
 8010291939,
 467699908633,
 306744967360,
 165977226682,
 969580736643,
 841972972819,
 905686310953,
 588470458133,
 932933792706,
 9331617414,
 233360798993,
 577231001724,
 306812957588,
 940344120589,
 262938238805,
 453224620619,
 276457965703,
 225427453479,
 299651588447,
 643328940448,
 639777718944,
 809911416060,
 461935869735,
 15541928459,
 799888457439,
 273932708391,
 133435224329,
 674630813541,
 411275375881,
 213461228624,
 863568200202,
 372713683329,
 590484297138,
 619239921904,
 177645720141,
 882897704707,
 548530801142,
 474616090914,
 826200963784]

In [279]:

data.to_csv("convert.csv")

In [280]:
xtrain,xtest,ytrain,ytest=train_test_split(data,y,test_size=0.2,shuffle=33)

In [281]:
model=RandomForestClassifier()
model.fit(xtrain,ytrain)

RandomForestClassifier()

In [282]:
enc(xtest)

In [283]:
tt=model.predict(xtest)
tt

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1], dtype=int64)

In [284]:
test=pd.read_csv("test.csv", na_values=' ')
test.drop("Loan_ID",axis=1,inplace=True)
test
test = test.fillna(1)
enc(test)

In [285]:
te=model.predict(test)
te

array([1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1], dtype=int64)

In [286]:
print(data.columns)
print(test.columns)

Index(['Gender', 'Married', 'Dependents', 'Education', 'Self_Employed',
       'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area'],
      dtype='object')
Index(['Gender', 'Married', 'Dependents', 'Education', 'Self_Employed',
       'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area'],
      dtype='object')

In [287]:
acc_grid_random=accuracy_score(ytest,tt)
acc_grid_random

0.7967479674796748

In [288]:
x_train,x_test,y_train,y_test=train_test_split(data,y,test_size=0.2,random_state=42)

In [289]:
# model.predict(y_train.values.reshape(-1, 1))
ac=model.predict(x_test)
ac

array([1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1], dtype=int64)

In [290]:
acc_grid_random=accuracy_score(y_test,ac)
acc_grid_random

0.959349593495935

In [291]:
data

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,1,0,0,1,0,5849,0.0,1.0,360.0,1.0,1
1,1,1,1,1,0,4583,1508.0,128.0,360.0,1.0,0
2,1,1,0,1,1,3000,0.0,66.0,360.0,1.0,1
3,1,1,0,0,0,2583,2358.0,120.0,360.0,1.0,1
4,1,0,0,1,0,6000,0.0,141.0,360.0,1.0,1
...,...,...,...,...,...,...,...,...,...,...,...
609,0,0,0,1,0,2900,0.0,71.0,360.0,1.0,0
610,1,1,4,1,0,4106,0.0,40.0,180.0,1.0,0
611,1,1,1,1,0,8072,240.0,253.0,360.0,1.0,1
612,1,1,2,1,0,7583,0.0,187.0,360.0,1.0,1
613,0,0,0,1,1,4583,0.0,133.0,360.0,0.0,2

In [293]:
val=data[["ApplicantIncome","CoapplicantIncome"]]
num_val=val["LoanAmount"]

KeyError: 'LoanAmount'

In [ ]:

val.drop("LoanAmount",axis=1,inplace=True)

In [294]:
num_val

0        1.0
1      128.0
2       66.0
3      120.0
4      141.0
       ...
609     71.0
610     40.0
611    253.0
612    187.0
613    133.0
Name: LoanAmount, Length: 614, dtype: float64

In [204]:
reg=LinearRegression()
reg.fit(val,num_val)

LinearRegression()

In [221]:
xtra,xtes,ytra,ytes=train_test_split(data,num_val,test_size=0.2,shuffle=30)

In [222]:
ytra.shape

(491,)

In [234]:
# op=
ac=reg.predict(xtes)
ac

array([129.07229049, 161.77804973, 127.9726294 , 580.24155127,
       136.3532216 ,  80.21762632, 146.84413191, 126.31619084,
       107.05142871, 244.43105261, 115.20970283, 137.05078424,
       104.30763891, 111.42337206, 132.87498308, 151.75131635,
       119.00373551, 150.33111531, 114.04658697, 120.61206349,
        93.88322832, 394.28425801, 130.50736195,  78.3327179 ,
       136.90954256, 135.87665545, 170.65712228, 152.91985977,
       130.88297032, 142.96039675, 145.97699496, 157.30116987,
       222.60273908, 115.94914492, 150.26969273, 116.69084345,
       440.8707975 ,  68.3135398 , 101.39322958, 142.01467414,
       133.05543023, 100.92060557, 117.43895465, 131.22162928,
       123.25114529, 105.16299871, 154.90221309, 509.33114598,
        99.34188944,  99.32241168, 206.46506184, 115.1368076 ,
       155.34324725, 103.22497725, 184.13650304, 144.07859139,
       127.43725936, 138.52882013, 125.21205438, 101.65925804,
       110.78489375, 107.07045055, 130.89283553, 116.58980242,
       157.5735977 , 128.37677665, 126.31694065, 155.23198293,
       131.23392775, 112.47008428, 136.20407623, 113.40353303,
       341.66190814, 134.87747463, 134.03327333, 166.47634256,
       146.00976493, 105.988507  , 112.48231701, 107.75170912,
        88.89877056, 255.83457931, 101.21068884,  96.48951703,
       146.99068751, 197.4364806 , 129.06857209, 140.3105974 ,
       185.37712054, 110.63828317, 119.94743896, 360.77578639,
       134.08216112,  99.71583669, 136.33207042, 146.22007791,
        92.7749318 , 131.9780472 , 143.06650879, 161.18694323,
       122.45441155, 159.47231138, 112.57264376, 116.40077203,
       234.89778194, 136.12357496, 180.5219645 , 107.16134984,
       131.64407212, 126.99583217, 110.54401268, 104.97314333,
       151.55351252, 201.4774903 , 109.43204208, 210.8076957 ,
       151.579018  , 176.89824385, 175.30683987, 131.24091692,
       145.45536711, 141.33163583, 175.16924504])

In [227]:
ytes

392    120.0
327    184.0
610     40.0
333    490.0
198    113.0
       ...
348    259.0
527    161.0
591    205.0
448    150.0
25     191.0
Name: LoanAmount, Length: 123, dtype: float64

In [235]:
acc=r2_score(ytes,ac)
acc

0.36596649466973064